In [1]:
import numpy as np

In [2]:
arr=np.arange(9.0).reshape(3, 3)
(arr)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [4]:
arr1=np.arange(12.0).reshape(4, 3)
(arr)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [5]:
(arr+arr1)

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.]])

In [6]:
arr3=np.sort(arr/2==0)
(arr)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [8]:
import pandas as pd

In [11]:
mydataset={'CARS' :["BMW", "VOLVO", "FORD"], 'PASSINGS':[3, 7, 2]}
myvar=pd.DataFrame(mydataset)
(myvar)I

CARS  PASSINGS
0    BMW         3
1  VOLVO         7
2   FORD         2

In [12]:
print(pd.__version__)

2.1.4


In [13]:
a=[1, 7, 2]
myvar=pd.Series(a)
(a)

[1, 7, 2]

In [14]:
(myvar[0])

1

In [15]:
(myvar[1])

7

In [17]:
a=[1, 7, 2]
myvar=pd.Series(a, index=["A", "B", "C"])
(myvar)

A    1
B    7
C    2
dtype: int64

In [19]:
(myvar["B"])

7

In [20]:
calories={"day1":420, "day2":360, "day3":240}
myvar=pd.Series(calories)
(myvar)

day1    420
day2    360
day3    240
dtype: int64

In [5]:
import pandas as pd

In [3]:
calories={"day1":420, "day2":360, "day3":240}
myvar=pd.Series(calories, index=["day1", "day3"])
(myvar)

day1    420
day3    240
dtype: int64

In [4]:
first_series=pd.Series([2, 4, 6, 8])
(first_series)

0    2
1    4
2    6
3    8
dtype: int64

In [6]:
number_series=pd.Series([2, 3, 5, 6, 8], index=['a', 'b', 'd', 'e', 'f'], name='Number')
(number_series)

a    2
b    3
d    5
e    6
f    8
Name: Number, dtype: int64

In [1]:
import pandas as pd

In [2]:
second_series=pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'], name='Table')
(second_series)

a    1
b    2
c    3
d    4
e    5
Name: Table, dtype: int64

In [5]:
(second_series[0:4:2])

a    1
c    3
Name: Table, dtype: int64

In [6]:
(second_series[0:0:2])

Series([], Name: Table, dtype: int64)

In [7]:
(second_series[1:4:1])

b    2
c    3
d    4
Name: Table, dtype: int64

In [11]:
(second_series[::2])

a    1
c    3
e    5
Name: Table, dtype: int64

In [12]:
(second_series[1::])

b    2
c    3
d    4
e    5
Name: Table, dtype: int64

In [3]:
import pandas as pd

In [4]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

(myvar)

calories  duration
0       420        50
1       380        40
2       390        45

In [6]:
data = {
    "Students":["Ankit", "Bhavesh", "Chetan"],
    "Marks":[99, 85, 71]
}
data=pd.DataFrame(data)
(data)

Students  Marks
0    Ankit     99
1  Bhavesh     85
2   Chetan     71

In [9]:
(data.loc[1])

Students    Bhavesh
Marks            85
Name: 1, dtype: object

In [10]:
(data.loc[0])

Students    Ankit
Marks          99
Name: 0, dtype: object

In [12]:
(data.loc[[1, 0]])

Students  Marks
1  Bhavesh     85
0    Ankit     99

In [15]:
data = {
    "Students":["Ankit", "Bhavesh", "Chetan"],
    "Marks":[99, 85, 71]
}
#data=pd.DataFrame(data)
data = pd.DataFrame(data, index = ["1", "2", "3"])
(data)

Students  Marks
1    Ankit     99
2  Bhavesh     85
3   Chetan     71

In [19]:
(data.loc["1"])

Students    Ankit
Marks          99
Name: 1, dtype: object

In [20]:
(data.loc["3"])

Students    Chetan
Marks           71
Name: 3, dtype: object

In [2]:
import pandas as pd
import numpy as np
ser=np.arange(10, 15)
serobj=pd.Series(index=ser, data=ser*5)
(serobj)

10    50
11    55
12    60
13    65
14    70
dtype: int32

In [3]:
series_1=pd.Series([2, 4, 6, 8])
series_2=pd.Series([10, 12, 14, 16])
series_1=pd.concat([series_1, series_2], axis=0)
(series_1)

0     2
1     4
2     6
3     8
0    10
1    12
2    14
3    16
dtype: int64

In [4]:
series_1=pd.Series([2, 4, 6, 8])
series_2=pd.Series([10, 12, 14, 16])
series_1=pd.concat([series_1, series_2], axis=1)
(series_1)

0   1
0  2  10
1  4  12
2  6  14
3  8  16

In [41]:
a=[1, 7, 2, 3, 4, 5, 6, 8, 9, 12]
myvar=pd.Series(a)
(a[-1:-4:-1])

[12, 9, 8]

In [43]:
info={"x":0,"y":1, "z":2}
info=pd.Series(info)
(info)

x    0
y    1
z    2
dtype: int64

In [2]:
import pandas as pd
import numpy as np
data={'a':0., 'b':1., 'c':2,}
s=pd.Series(data, index=['b', 'c', 'd', 'a'])
(s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [4]:
import pandas as pd
d=[['a', 20],['b', 21],['c', 21],['d', 21]]
df1=pd.DataFrame(d, columns=['Name','grade'])
print(df1)

  Name  grade
0    a     20
1    b     21
2    c     21
3    d     21
